### ISSUE TITLE
Whitelist as wildcard

### ISSUE THREAD

**Issue by evlsmurf** [badsgahhl/pihole-browser-extension#26]
Is there a way you can also add the ability to whitelist domain as wildcard like we can through admin panel

**Comment by badsgahhl** [comment]
It's something I've discussed before. Generally speaking, this is not something that belongs in the extension per se. The feature that is currently built in is only meant to give the user the possibility to unblock a page that is blocked often.
That you can release all subdomains with the extension is actually not what you want to do with it, but rather you should do it yourself in the PiHole interface.

Apart from that there is not really room for it in the current UI. There might be a major change in the popup, but if the subdomain whitelist will be included I don't think so.

Translated with www.DeepL.com/Translator (free version)
