### ISSUE TITLE
Plugin Err on Firefox - Pihole Admin Panel behind Traefik and with SSO Boreale for traefik

### ISSUE THREAD

**Issue by SirTerrific** [badsgahhl/pihole-browser-extension#27]
**Describe the bug**
Plugin still red with Err

**Expected behavior**
I have my pi-hole Admin panel behind Traefik v1 Reverse Proxy and SSO Boreale (https://github.com/lewazo/boreale). I remembered during the first version of the plugin I was able to use it and one day it stopped working. 

I correctly setuped the API token (no space etc..) I have the good URL with the one I access to my Pihole Admin.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/12296919/88706321-3ce3f900-d100-11ea-9428-4a141dc82dfd.PNG)

**Desktop (please complete the following information):**
- Switch for PiHole: 2.2.8
- Operating System: Win32
- Browser: Mozilla Firefox 78.0

**Additional context**

**Comment by badsgahhl** [comment]
If you can call the URL that you have set in the settings in your browser without everything, then it should work with the extension. How the extension accesses the PiHole has never changed and is even relatively identical to the first version.

Plus, if you can't open http://<your-url>/admin/api.php ,then pls try the next step here:

Firefox is a bit stupid for debugging. I would recommend you to install the extension again 1:1 in chrome with your settings.
Then open the popup and right-click into the popup and press " inspect". In the new window go to the console and put a screenshoot of it here in the issue.

**Comment by SirTerrific** [comment]
Hi, 

Thanks for your help. 

So I tried on Chrome to inspect and I had an error 401 because of I was not authentified through SSO boreale. After being authentified I was able to use the plugin.

That's remind me that I'm using Firefox Multi-Account Containers and I put my personal domain in another "container" so your plugin can't read the cookie for the SSO. After disable Firefox Multi-Account Containers the plugin works well. 

I don't think if it's possible to interact with Firefox Multi-Account Containers in order to permit Pihole Swith to have access to a "container" ? 

Thanks.

**Comment by badsgahhl** [comment]
The extension won't access anything in the containers directly. This extension is a low level feature that is deeply implemented in firefox that won't allow this.

But if you open a new tab that is not a container, shouldn't it work then? Bcs you then have a normal tab and the cookie should be available globally.

**Comment by SirTerrific** [comment]
> 
> 
> The extension won't access anything in the containers directly. This extension is a low level feature that is deeply implemented in firefox that won't allow this.
> 
> But if you open a new tab that is not a container, shouldn't it work then? Bcs you then have a normal tab and the cookie should be available globally.

Hi, 

Yes. That's right. It works

It was just an interrogation.

**Comment by badsgahhl** [comment]
Cool, I close the issue here. Enjoy the extension.
For any other problem, open another issue.
