### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jaspov** [badsgahhl/pihole-browser-extension#33]
I keep getting an error. I am sure api is correct, checked the whole number, no spaces and no error
URL I use is http://192.168.178.44/admin (no https), also tried http://192.168.178.44/admin/ and http://192.168.178.44/ however always error

Switch for PiHole: 2.2.11
Operating System: Win32
Browser: Mozilla Firefox 82.0

**Comment by badsgahhl** [comment]
Hey,
please visit the following url:

`about:devtools-toolbox?type=extension&id={a4cc20af-d30a-4758-a799-2089ce45f452}`

In the top left corner you should see "This Firefox (82.0)". Under that there should be some tabs. Please send screenshoot of the "Console" and "Networkanalysis" tab.

**Comment by jaspov** [comment]
Here they are. Blurred part of what  I think is the API key

![image](https://user-images.githubusercontent.com/9215855/96770830-238dd880-13e1-11eb-8feb-c1347b356978.png)
![image](https://user-images.githubusercontent.com/9215855/96770848-2c7eaa00-13e1-11eb-9aa4-d29f98ccf0aa.png)

**Comment by badsgahhl** [comment]
Which Url did u use for those screenshots?

The errors basically indicates for me that the url is still the wrong one. 

You can test the domain by yourself.

For example if you input http://192.168.178.2/admin you should go by yourself to http://192.168.178.2/admin/api.php.

You should see some results on the page there that look like this:

`"domains_being_blocked":197998,"dns_queries_today":59658,"ads_blocked_today":16645,"ads_percentage_today":27.900702,"unique_domains":21947,"queries_forwarded":22670,"queries_cached":19218,"clients_ever_seen":38,"unique_clients":23,"dns_queries_all_types":59658,"reply_NODATA":6400,"reply_NXDOMAIN":2129,"reply_CNAME":14152,"reply_IP":42267,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1602986003,"relative":{"days":4,"hours":13,"minutes":41}}}`

**Comment by jaspov** [comment]
Thanks for that. I used all the URLS from the opening post. Checked dashboard and there was something strange with it. Rebooted, updated linux and that seems to have solved it! So plugin working fine, issue on the pi-hole side. thx!
