### ISSUE TITLE
Two suggestions: - Context menu alternative to top bar icon / - Keyboard shortcuts 

### ISSUE THREAD

**Issue by FlorentLM** [badsgahhl/pihole-browser-extension#37]
Hi,

Thanks for this extension, it's very nice!

It would be cool to have the possibility to get it in the context menu rather than in the top bar, I think it looks cleaner without any colored icons always there :)

Also, keyboard shortcuts for toggling PiHole and Adding to blacklist / whitelist would be amazing. For instance, this could even be used by a macOS touchbar custom button (with help of the amazing BetterTouchTool app)

Cheers

**Comment by badsgahhl** [comment]
Hey,

the feature with the hotkeys is definitely something to look at.

What I don't understand is what you mean with "context menu" instead of the top bar.

**Comment by FlorentLM** [comment]
Nice, looking forward to that 👍

Context menu = right click menu :)

**Comment by badsgahhl** [comment]
Do you mean the context menu if you right-click into a page or which one?

**Comment by badsgahhl** [comment]
Available with v2.3.
