### ISSUE TITLE
Add-on not working when there's no web password/API key

### ISSUE THREAD

**Issue by BrianPeek** [badsgahhl/pihole-browser-extension#38]
**Describe the bug**
Add-on not working when there's no web password/API key

**To Reproduce**
1. Remove the web password from the pihole config
2. Use the add-on to disable PiHole

**Expected behavior**
Switch to work, instead shows "Err"

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 85.0b7

**Additional context**
Seems to work just fine if I add a web password to the admin panel and supply the API key to the add-on.  And it seems this recently broke, was working a few days ago.

Thanks for this great add-on!

**Comment by badsgahhl** [comment]
Hell no. You're right.
Fixes in 2.3.1.
Thanks for reporting.

**Comment by BrianPeek** [comment]
Awesome, thank you!

**Comment by BrianPeek** [comment]
Sorry for the double comment.  Just updated/tested, working great!

**Comment by quadcom** [comment]
Broken in v2.3.3
