### ISSUE TITLE
No password set means no API key needed but still throws an error

### ISSUE THREAD

**Issue by quadcom** [badsgahhl/pihole-browser-extension#44]
v2.3.3

**Describe the bug**
If PiHole has no password set it will not generate an API key for the extension to use.

**To Reproduce**
Steps to reproduce the behaviour:
Disable the PiHole password and try to see the API key, "No password set" will be shown.
Install the extension and try to add PiHole address without providing an API key

**Expected behaviour**
Allow for configuration with no API key present

**Comment by badsgahhl** [comment]
The extension works fine without setting an API Key.
(Extension v.2.3.3 and PiHole WebInterface v5.4)
