### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by schklom** [badsgahhl/pihole-browser-extension#50]
**Describe the bug**
Complete failure to do anything.

**To Reproduce**
1. Fill Pi-hole's address `http://pi.hole:8888/admin`
2. Fill api token correctly
3. Try to click on the addon's red button on a random webpage
4. Nothing happens

**Expected behavior**
Turn off PI-hole for a bit

**Desktop (please complete the following information):**
Switch for PiHole: 2.3.3
Operating System: Win32
Browser: Mozilla Firefox 92.0

**Additional context**
I think the error comes from the custom port 8888.

**Comment by dwemel** [comment]
Same issue here, but with standard port... It stopped working about 1 week ago.

**Comment by badsgahhl** [comment]
Hello, thanks for reporting the issue.

Unfortunately the extension works like it should on my side. I also checked the compatibility to the current PiHole Version v5.6, and everything is fine there.

The extension also accepts custom ports.

**Comment by dwemel** [comment]
I just changed the PiHole Address to http://openhab/admin/, and now all seems to work fine.
Hope this can help others as well :-)
________________________________

**Comment by schklom** [comment]
It looks like it doesn't accept `http://pi.hole:8888/admin` for some reason, although this url works well on my browser.

`http://pihole_ip_address:8888/admin` works fine.
