### ISSUE TITLE
2.3.4 spamming pihole - causing CPU spikes

### ISSUE THREAD

**Issue by RoggerFabri** [badsgahhl/pihole-browser-extension#52]
The last version (2.3.4) which introduced the connection check is spamming pihole with requests, causing CPU spikes.

**Comment by badsgahhl** [comment]
Spamming with request?

Can u address the issue I little bit more concretely. For example when this issue happens?

Basically the check is only triggered after opening the settings, pressing one of the settings tabs or after a delay after entering the IP. 

I couldn't find a case where it would cause multiple requests (or at least a huge amount) that would be critical. The same requests are used in the popup for example.

**Comment by RoggerFabri** [comment]
Hmm so there's something else that changed on the last version that is spamming pihole with a lot of requests.
I noticed on my logging that since yesterday my rpis CPU started to spike, if I disable the extension, the spikes are gone and CPU is back to normal. So maybe it's the checker to know whether pihole is on or not?

**Comment by badsgahhl** [comment]
Probably the background checker. But this hasn't changed since release of the extension.

Did you upgrade you PiHole in the last time? It's often happening that after upgrading PiHole API Request can cause high loads for whatever reason. That's a common issue I noticed in my Repo's issues.

**Comment by RoggerFabri** [comment]
You're right, I just checked, and the background checker hasn't changed.
I've recently upgraded to v5.9, so maybe the issue is in the pihole version itself, not your extension. Is there any fix that you are aware of?

**Comment by badsgahhl** [comment]
I really don't know if there is a issue yet at one of the pihole Repositories. 

The fact of the performance spikes is just something that I generally noticed. And it's happening after every upgrade sometime. So nothing related with 5.9 probably.

**Comment by RoggerFabri** [comment]
Ok, I'll keep an eye on it. Thanks for replying so quickly.
