### ISSUE TITLE
Cannot change duration

### ISSUE THREAD

**Issue by upD8R** [badsgahhl/pihole-browser-extension#57]
**Describe the bug**
I cannot change the default of 10s. Whatver duration is already set (on some boxes I have previously configured 600s) I cannot change the duration anymore. Whatever duration is used, the enabling of Pihole happens after just a few seconds again.

**To Reproduce**
Try to to change the duration by entering numbers or using the up and down arrows.
If I close the popup it defaults back to 10s (or the previous value) only.
Disabling PiHole by clicking the icon => slider only lasts a few seconds, even if a much bigger time is set.

**Expected behavior**
Accept any time (my default is usually 600s)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome 97.0.4692.71
 - Extension: 3.0.1
 - Pihole v5.8.1

**Additional context**
This issue is not related to Win 11, it also happens on my Win 10 boxes.

**Comment by badsgahhl** [comment]
Hi,
unfortunately I cannot reproduce this behaviour in 3.0.1. If i change the default disable time either in the settings or in the popup it self, it will be used in the disabling process.

![image](https://user-images.githubusercontent.com/28596891/148436208-3bc425d4-86fc-4fa6-bfb2-03241b2b6940.png)
![image](https://user-images.githubusercontent.com/28596891/148436222-f80c93a3-1db8-4d48-995d-7d2af95e7d9b.png)

**Comment by upD8R** [comment]
Thanks for the quick response, indeed I can change it in the settings, so I set it to 600s now. So this seems to be fine.
Nevertheless, if I disable Pihole now in the popup it diables it (for 600s) but the icon turns back to "on" after a few seconds, Pihole itself is still disabled.
In the screenshot you can see that the status is different in the icon and in Pihole itself,
![image](https://user-images.githubusercontent.com/39015615/148440271-bd2290c8-ab0a-4efe-9c66-36dcf0c1f68d.png)

**Comment by badsgahhl** [comment]
Yes this is another bug which is already discussed here https://github.com/pi-hole/AdminLTE/issues/2051#issuecomment-1006836175
and there
https://github.com/badsgahhl/pihole-browser-extension/issues/54#issuecomment-1006836461

**Comment by upD8R** [comment]
I see, thanks, Then we can close here! ;)
