### ISSUE TITLE
Was working properly, now isn't

### ISSUE THREAD

**Issue by lithophone** [badsgahhl/pihole-browser-extension#58]
I found this extension and thought it would be an easy way for my wife to disable the Pi-Hole when needed.  I installed it on my laptop to test and loved it.  I then installed on her laptop as well with identical settings and assumed everything was good to go.  Just tried to disable now from my laptop, a couple days later, and it is not working at all.  Is there a conflict when installed on multiple computers?  Both computers running Chrome browsers in Windows 10.
----------
EDIT:
I wasn't 100% accurate in my writing before I accidentally hit submit.  The Pi-Hole does in fact disable, but the extension quickly reverts to on, giving the appearance that it is not disabled.

**Comment by badsgahhl** [comment]
Hi,
this probably related to this issue: https://github.com/badsgahhl/pihole-browser-extension/issues/54

The current version of PiHole seems to have a bug and doesn't return the correct PiHole status which is then displayed wrong in the extension.

**Comment by lithophone** [comment]
I had seen that, but thought I had a completely different problem due to the timing of my adding a second computer to control machines.  Will keep an eye out for updates.
But just to be clear--when everything is working properly, I should be able to control the Pi-Hole from either of the 2 laptops?  And the status will show properly on both?
Thank you very much!
    On Saturday, January 8, 2022, 10:04:45 AM EST, Pascal Glaser ***@***.***> wrote:  
 
 


Hi,
this probably related to this issue: #54

The current version of PiHole seems to have a bug and doesn't return the correct PiHole status which is then displayed wrong in the extension.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HeyRobb** [comment]
Same issue here: using latest version of PiHole DNS (as of today).. Extension shoes a successful connection, but toggling to On/off (either in the extension or in WebGUI) does not get reflected in the opposite side.

**Comment by badsgahhl** [comment]
> But just to be clear--when everything is working properly, I should be able to control the Pi-Hole from either of the 2 laptops?  And the status will show properly on both?

Yes it will be correct after the next PiHole update. The usage of multiple extensions with one PiHole should just work like you would expect.

**Comment by badsgahhl** [comment]
> Same issue here: using latest version of PiHole DNS (as of today).. Extension shows a successful connection, but toggling to On/off (either in the extension or in WebGUI) does not get reflected in the opposite side

See #54 for further infos.
