### ISSUE TITLE
no longer reports "ON" only displays off

### ISSUE THREAD

**Issue by CanonCan** [badsgahhl/pihole-browser-extension#60]
**Describe the bug**
The Plugin No longer works it always displays off when when in settings it says connection to PiHole Server was succesful
Not sure if a recent chrome update or Pihole update broke the connection but its affecting my chrome on all my systems, ChromeOS, Windows 10, Fedora Linux, MacOS

**To Reproduce**
1. Pi icon shows off '...'
2. Click on enable switch and it satys on until page refresh or change of web pages

**Screenshots**

**Desktop (please complete the following information):**
Chrome OS using Chrome Browser, Windows 10 Chrome Browser

PiHole Browser Extension: 3.0.2
Operating System: Linux x86_64
Browser: Chrome/Chromium 97.0.4692.77
Pi-hole v5.8.1 FTL v5.13 Web Interface v5.10.
![Screenshot 2022-01-09 22 02 44](https://user-images.githubusercontent.com/31594024/148720392-c6c28daf-f533-4a5b-b67d-40a3a299d877.png)
1

**Comment by sarvasana** [comment]
Same here!

**Comment by badsgahhl** [comment]
https://github.com/badsgahhl/pihole-browser-extension/issues/54#issuecomment-1008338921

**Comment by Erebus999** [comment]
Same Problem after Update PiHole 
Pi-hole v5.8.1 FTL v5.13 Web Interface v5.10.1

**Comment by badsgahhl** [comment]
> Same Problem after Update PiHole
Pi-hole v5.8.1 FTL v5.13 Web Interface v5.10.1

It's fixed with the **next** PiHole version. Probably Web 5.10.2
