### ISSUE TITLE
PiHole Switch zeigt falschen Status an

### ISSUE THREAD

**Issue by jl61** [badsgahhl/pihole-browser-extension#63]
**Describe the bug**
Der Status des PiHole ist "active", aber PiHole Switch zeigt "off" an.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.2 beta
 - Browser: Chrome
 - Version 97.0.4692.71
 - Pi-hole v5.8.1 FTL v5.13 Web Interface v5.10.1

**Additional context**
PiHole Switch hat bis vor wenigen Tagen einwandfrei funktioniert, aber plötzlich wird der falsche Status angezeigt.
Wenn ich in der Erweiterung PiHole aktiviere, wird kurz "on" angezeigt, aber nach 2 Sekunden wechselt er wieder auf "off".

Ich habe Chrome auf Version 97 aktualisiert und PiHole ebenfalls aktualisiert. Ich kann nicht sagen, ob der Fehler bei einem der Updates aufgetreten ist.

![pic35](https://user-images.githubusercontent.com/46631320/148828681-602fc411-6dc9-472e-b00c-486a9a4e044b.jpg)
![pic36](https://user-images.githubusercontent.com/46631320/148828696-f25b1400-bb58-4b5d-94fe-660c82112620.jpg)
![pic37](https://user-images.githubusercontent.com/46631320/148828702-23e0f78f-c5d4-4ccf-833f-f66485050693.jpg)

**Comment by badsgahhl** [comment]
Duplicate of #54
