### ISSUE TITLE
Disabled with Err

### ISSUE THREAD

**Issue by SDeGonge** [badsgahhl/pihole-browser-extension#76]
Not sure if this is a but or a problem with my system.
PiHole extension displays Err on the task bar icon.
The popup to turn it on/off is off and gray, cannot click and turn it on.
Configuration is correct. IP and API Key is entered correctly and "Connection successful Core: v5.15.3 FTL: v5.20.1 Web: v5.18.3" is displayed.

**To Reproduce**
See above description

**Expected behavior**
Expected to click and be able to turn on/off

**Screenshots**
![image](https://user-images.githubusercontent.com/14916505/215271211-a8504fe7-436c-4b56-ad77-7485957e4d42.png)
![image](https://user-images.githubusercontent.com/14916505/215271234-021fe952-850e-40e3-b3c6-72b343467409.png)

**Desktop (please complete the following information):**
 - OS: Windows V11
 - Browser: Chrome V109
 - Pi OS: Proxmox LCX (Debian)

**Additional context**
I tried deleting the extension and re-adding but the problem remains.

**Comment by badsgahhl** [comment]
Hey,
the extension seems to work at my end here with the current pihole version.
To further debug the issue please follow the following steps:

1. Go to chrome://extensions/
2. Enable Developer Mode and click on the background.html link of the pihole extension
![image](https://user-images.githubusercontent.com/28596891/215271762-d71f781d-cbc0-4c6f-bd9e-543ac96d3170.png)
4. From here on click onto the network tab in the open window and select one of the periodic network requests.
5. Click on preview
![image](https://user-images.githubusercontent.com/28596891/215271835-f2cd2e3e-bc4e-4302-851a-ca06ac465ccf.png)

Please then make a screenshot and submit the result you get there.

**Comment by SDeGonge** [comment]
![image](https://user-images.githubusercontent.com/14916505/215272349-bbcbbd2d-0040-4713-8237-dc393e011d08.png)
![image](https://user-images.githubusercontent.com/14916505/215272363-db1acb8a-01e4-4e1a-a134-ee2b62a8bbdd.png)

Doublechecked the API Token and it matches Pi-Hole.
I also noticed that the "connection successful" indication does not check for a valid API, it seems to check the IP and the length/format of the API only.

**Comment by badsgahhl** [comment]
Can u maybe make a screenshot of the "Headers" Section?
![image](https://user-images.githubusercontent.com/28596891/215272718-88c8d40e-a507-4283-a986-586348855f30.png)
Actually never saw a "redirector".

**Comment by badsgahhl** [comment]
> I also noticed that the "connection successful" indication does not check for a valid API, it seems to check the IP and the length/format of the API only.

Yes it's a really "basic" check, just to validate the inputs and if the url is correct.

**Comment by SDeGonge** [comment]
![image](https://user-images.githubusercontent.com/14916505/215272814-cdf7846c-96ff-4d27-83c5-d99593e0e9cb.png)

![image](https://user-images.githubusercontent.com/14916505/215272754-1c320a69-a8d3-4b24-a5f5-ec03e840078f.png)

**Comment by badsgahhl** [comment]
Just from my viewpoint, i would assume that the redirect in your nginx is misconfigured. The extension basically uses that normal JavaScript fetch api for requests, so if you correctly redirect requests via nginx it should be able to resolve them. However it seems that for the Request URL you see there your nginx is doing a request to a route that does not exists.

**Comment by SDeGonge** [comment]
Is nginx part of pi-hole, chrome, Java?

**Comment by badsgahhl** [comment]
NGINX is a reverse proxy that is not default part of pihole, it can basically handle web requests or serve websites and is like it seems installed on the machine you installed pihole. I cannot give u further details there, because thats in your hand what you have installed or how you installed pihole at the system. Normally pihole uses something called lightttp to serve its admin site and api, not nginx.

**Comment by badsgahhl** [comment]
And also normally it shouldn't redirect request to /redirector.

**Comment by SDeGonge** [comment]
> NGINX is a reverse proxy that is not default part of pihole, it can basically handle web requests or serve websites and is like it seems installed on the machine you installed pihole. I cannot give u further details there, because thats in your hand what you have installed or how you installed pihole at the system. Normally pihole uses something called lightttp to serve its admin site and api, not nginx.

Thanks. I just checked my wife's machine and the extension is working fine there so it is indeed related to my machine and not your extension. I'll post back here if I figure out the problem. Thanks for directing me to the source of the problem.

**Comment by SDeGonge** [comment]
Problem solved.
Chrome: -> Settings -> Reset and clean up -> Restore settings to their original defaults -> Reset settings
Re-enable the extension and everything is now working :)
