### ISSUE TITLE
Clear Chromne DNS Cache when Temporarily Disabling PiHole

### ISSUE THREAD

**Issue by JaronrH** [badsgahhl/pihole-browser-extension#77]
**Is your feature request related to a problem? Please describe.**
While I can easily disable PiHole with your extension, I've found that I also need to clear DNS in Chrome to get a page to load (chrome://net-internals/#dns).  It would be great if I could skip that extra step!

**Describe the solution you'd like**
If possible, clear the DNS cache [like I'm manually doing at chrome://net-internals/#dns] before trying to reload the page (not sure if the extension API allows you to do this or not!).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Thanks for your consideration!

**Comment by badsgahhl** [comment]
Not possible directly without starting chrome in a special way, which is not really practicall.
