### ISSUE TITLE
Extension can't connect to pihole

### ISSUE THREAD

**Issue by Thelk641** [badsgahhl/pihole-browser-extension#82]
Installed the extension on firefox and edge (using the chrome store for that one). Gave it the API and the webadress of pihole's gui (http://192.168.1.33). Extension says : "Connection not successfully" and nothing happens.

Pihole is running in docker, in case it might be causing the issue.

Firefox 112.0.2
Windows 10
Docker Tag 2023.03.1 
Pi-hole v5.16.2 
FTL v5.22 
Web Interface v5.19

**Comment by Brandon-Roff** [comment]
Good Day,

I have had the same issue try the below

http://192.168.1.133/admin
APIKEY

This is because of the location of pihole api query URL

any issues let me know

**Comment by LittleFreak** [comment]
> Good Day,
> 
> I have had the same issue try the below
> 
> http://192.168.1.133/admin APIKEY
> 
> This is because of the location of pihole api query URL
> 
> any issues let me know

have you changed the port of your lighttpd (pihole) server?

**Comment by Hoempi** [comment]
> Good Day,
> 
> I have had the same issue try the below
> 
> http://192.168.1.133/admin APIKEY
> 
> This is because of the location of pihole api query URL
> 
> any issues let me know

This worked for me as well. Thank you very much!
