### ISSUE TITLE
This extension may soon no longer be supported in Chrome

### ISSUE THREAD

**Issue by t1m0thyj** [badsgahhl/pihole-browser-extension#92]
Chrome is phasing out support for Manifest V2 extensions. In order to continue working in Chrome this extension will need to migrate to Manifest V3: https://developer.chrome.com/docs/extensions/develop/migrate

**Comment by AndreaLeidi** [comment]
Hope never dies but the latest update dates back to January 9, 2022. Sadly, I think it's time to consider this project abandoned.

**Comment by mpegram3rd** [comment]
There's a Draft PR started back earlier in this year on the `v4` branch (#86) that appears to be an attempt to fix the issue @badsgahhl  is there anything the user community can do to help get that over the finish line?

**Comment by badsgahhl** [comment]
I hope I find the time to look into it the upcoming weeks.

**Comment by AndreaLeidi** [comment]
Hi @badsgahhl and thanks! PiHole Browser Extension is very useful and well done.

**Comment by stanthewizzard** [comment]
yes very useful

**Comment by johnnykang** [comment]
just wondering if there is any update on this as 2024 is closing.

**Comment by badsgahhl** [comment]
As mentioned, I really don't use PiHole on my own anymore and therefore I reprioritize this project further low in my daily schedule. I started with the V4 Implementation but still needs fine-tuning. Mostly Manifest V3 ist breaking a lot of stuff. Really have to time when this is going to be released, sorry to say.

**Comment by t1m0thyj** [comment]
@badsgahhl Are you open to contributions to the extension? Since I actively use PiHole, I wouldn't mind daily driving the V4 implementation and opening a PR to fix whatever breaks.

**Comment by t1m0thyj** [comment]
Since the V4 branch has a lot of WIP refactoring, I've forked `master` branch and migrated it to support V3: https://github.com/badsgahhl/pihole-browser-extension/compare/master...t1m0thyj:pihole-browser-extension:master

With the changes I've made basic functionality is working. I'll keep testing my branch and see if I hit issues. All the behavior should be the same as original, except the check status interval changed from 15 to 30 seconds due to limitations of the `chrome.alarms` API.

**Comment by badsgahhl** [comment]
> Since the V4 branch has a lot of WIP refactoring, I've forked `master` branch instead and migrated it to use Manifest V3: [master...t1m0thyj:pihole-browser-extension:master](https://github.com/badsgahhl/pihole-browser-extension/compare/master...t1m0thyj:pihole-browser-extension:master)
> 
> With the changes I've made basic functionality is working. I'll keep testing my branch and see if I hit issues. All behavior should be same as original, except the check status interval changed from 15 to 30 seconds due to limitations of the `chrome.alarms` API.

Will look into that!

**Comment by badsgahhl** [comment]
Thanks a lot for the work! Updates will be pushed throw the stores in time.
